# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.9'
services:
  gateway:
    extends:
      file: ./services/gateway.yml
      service: gateway
    env_file:
      - ./.env
  rnc:
    extends:
      file: ./services/rnc.yml
      service: rnc
    env_file:
      - ./.env
  infodoc:
    extends:
      file: ./services/infodoc.yml
      service: infodoc
    env_file:
      - ./.env
  risco:
    extends:
      file: ./services/risco.yml
      service: risco
    env_file:
      - ./.env
  metaind:
    extends:
      file: ./services/metaind.yml
      service: metaind
    env_file:
      - ./.env
  auditplan:
    extends:
      file: ./services/auditplan.yml
      service: auditplan
    env_file:
      - ./.env
  tunnel:
    extends:
      file: ./services/tunnel.yml
      service: tunnel
networks:
  default:
    name: all4qms
