# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.9'
services:
  all4qmsmsgateway-app:
    image: all4qmsmsgateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - JHIPSTER_SLEEP=15 # gives time for microservices to boot before the gateway, the entire stack will be ready to accept incoming requests.
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
    ports:
      - 8080:8080
  all4qmsmsrnc-app:
    image: all4qmsmsrnc
    volumes:
      - /c/QMS/Anexos/DNC:/tmp/anexos/dnc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - JHIPSTER_SLEEP=30
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
    ports:
      - 8082:8082
  all4qmsmsinfodoc-app:
    image: all4qms-ms-infodoc
    volumes:
      - /c/QMS/Anexos/DOCS:/tmp/anexos/docs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - JHIPSTER_SLEEP=30
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
    ports:
      - 8083:8083
  all4qmsmsrisco-app:
    image: all4qmsmsrisco
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - JHIPSTER_SLEEP=30
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
    ports:
      - 8084:8084
  all4qmsmsgateway-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/all4qmsMsGateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=all4qmsMsGateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  jhipster-registry:
    image: jhipster/jhipster-registry:v7.3.0
    volumes:
      - ./central-server-config:/central-config
    environment:
      - JHIPSTER_SLEEP=5
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
      #- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      #- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      #- SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    ports:
      - 8761:8761
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiMWI0NWU0MDk3OWM3YmQ5MDc1YjNkOGU0ZDgyMWExZTEiLCJ0IjoiMTI0MzM0MzItOGUyOC00YjdhLTg5ZTEtODdiNGI5OWU1NGNiIiwicyI6IlkyVmpNMkkzTlRNdFptUm1PQzAwTm1FeUxUZ3hPV1V0TldVM1pUWTBNRFk0TW1NMCJ9
    depends_on:
      - all4qmsmsgateway-app
      - all4qmsmsrnc-app
networks:
  default:
    name: all4qms
