# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.9'
services:
  gateway:
    image: all4qmsmsgateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsMsGateway
      - JHIPSTER_SLEEP=30 # gives time for microservices to boot before the gateway, the entire stack will be ready to accept incoming requests.
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
    ports:
      - 8080:8080
  rnc:
    image: all4qmsmsrnc
    volumes:
      - /c/QMS/Anexos/DNC:/tmp/anexos/dnc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsnsrnc
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsnsrnc
      - JHIPSTER_SLEEP=40
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
      - SERVER_GATEWAY=http://gateway:8080
    ports:
      - 8082:8082
  infodoc:
    image: all4qms-ms-infodoc
    volumes:
      - /c/QMS/Anexos/DOCS:/tmp/anexos/docs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsinfodoc
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsinfodoc
      - JHIPSTER_SLEEP=50
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
    ports:
      - 8083:8083
  risco:
    image: all4qmsmsrisco
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsrisco
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsrisco
      - JHIPSTER_SLEEP=40
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
      - SERVER_RNC=http://rnc:8082
      - SERVER_GATEWAY=http://gateway:8080
    ports:
      - 8084:8084

  metaind:
    image: all4qmsmsmetaind
    volumes:
      - /c/QMS/Anexos/META:/tmp/anexos/meta
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsmetaind
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsmetaind
      - JHIPSTER_SLEEP=50
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
    ports:
      - 8085:8085
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8085/management/health
      interval: 5s
      timeout: 5s
      retries: 40
  auditplan:
    image: all4qmsmsauditplan
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsauditplan
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/all4qmsmsauditplan
      - JHIPSTER_SLEEP=60
      - QMS_REGISTRY_HOST=all4qms-registry.cthmprojetos.com
      - QMS_REGISTRY_PROTOCOLO=https
      - IA-HOST=https://all4qms-ia.cthmprojetos.com
    ports:
      - 8086:8086
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8086/management/health
      interval: 5s
      timeout: 5s
      retries: 40
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiMWI0NWU0MDk3OWM3YmQ5MDc1YjNkOGU0ZDgyMWExZTEiLCJ0IjoiMTI0MzM0MzItOGUyOC00YjdhLTg5ZTEtODdiNGI5OWU1NGNiIiwicyI6IlkyVmpNMkkzTlRNdFptUm1PQzAwTm1FeUxUZ3hPV1V0TldVM1pUWTBNRFk0TW1NMCJ9
networks:
  default:
    name: all4qms
