# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.9'
services:
  all4qmsmsgateway-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/jhipster/all4qmsMsGateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=all4qmsMsGateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
networks:
  default:
    name: all4qms
