export enum TabIdentifier {
  COPIA_CONTROLADA = 'COPIA_CONTROLADA',
  DISTRIBUICAO = 'DISTRIBUICAO',
  SOLICITACAO_VALIDACAO = 'SOLICITACAO_VALIDACAO',
  APROVACAO = 'APROVACAO',
  CANCELADO = 'CANCELADO',
  OBSOLETO = 'OBSOLETO',
  HOMOLOGADOS = 'HOMOLOGADOS',
}
