export type CompleteAnalysis = {
  description: string;
  meaning: string;
  probability: 'Baixo' | 'Médio' | 'Alto';
  severity: 'Baixo' | 'Médio' | 'Alto';
  useIshikawa: boolean;
  ishikawaCause: string;
  environment: string;
  manpower: string;
  machine: string;
  measurement: string;
  method: string;
  rawMaterial: string;
  useReasons: boolean;
  reasonCause: string;
  reasonEffect: string;
  reason1: string;
  reason2: string;
  reason3: string;
  reason4: string;
  reason5: string;
  actionDescription: string;
  actionDate: Date;
  responsibleId: number;
  verifyAction: boolean;
  actionVerificationDate: Date;
  actionVerifierId: number;
  implementationDate: Date;
  implementationResponsibleId: number;
  implemented: boolean;
  implementationDescription: string;
  efficacyVerificationDate: Date;
  efficacyResponsibleId: number;
  efficacyVerified: boolean;
  efficacyDescription: string;
};
