# Gateway service configuration
services:
  gateway:
    image: all4qmsmsgateway
    environment:
      - _JAVA_OPTIONS=${_JAVA_OPTIONS}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
      - SPRING_R2DBC_URL=${SPRING_R2DBC_URL}${DB_GATEWAY}
      - SPRING_LIQUIBASE_URL=${SPRING_LIQUIBASE_URL}${DB_GATEWAY}
      - JHIPSTER_SLEEP=${JHIPSTER_SLEEP}
      - QMS_REGISTRY_HOST=${QMS_REGISTRY_HOST}
      - QMS_REGISTRY_PROTOCOLO=${QMS_REGISTRY_PROTOCOLO}
      - PROXY_PORT=${PROXY_PORT}
      - GATEWAY_URL=${GATEWAY_URL}
      - GATEWAY_HOST=${GATEWAY_HOST}
    ports:
      - 9080:8080
