# Risco service configuration
services:
  risco:
    image: all4qmsmsrisco
    environment:
      - _JAVA_OPTIONS=${_JAVA_OPTIONS}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=${MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/${DB_RISCO}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://all4qmsmsgateway-postgresql:5432/${DB_RISCO}
      - JHIPSTER_SLEEP=${RISCO_SLEEP}
      - QMS_REGISTRY_HOST=${QMS_REGISTRY_HOST}
      - QMS_REGISTRY_PROTOCOLO=${QMS_REGISTRY_PROTOCOLO}
      - IA_HOST=${IA_HOST}
      - SERVER_RNC=${SERVER_RNC}
      - SERVER_GATEWAY=${SERVER_GATEWAY}
    ports:
      - 8084:8084
